Queries enhancement
expl0r3rgu1/mikasa pull request #4
Opened 2022-07-12 14:16 UTC by ValentinaPieri

2022-07-12 14:45 UTC, benedettapacilli requested changes

2022-07-12 14:45 UTC, benedettapacilli commented on queries.py
> +    'Ristock prodotto': 'UPDATE quantità SET quantità = %s WHERE cod_prodotto = %s AND cod_negozio = %s',
Restock

2022-07-12 14:45 UTC, benedettapacilli commented on queries.py
>      'Aggiungi confezione': 'INSERT INTO confezioni(cod_negozio, cod_alimento, quantità, prezzo_totale) VALUES (%s, %s, %s, %s)',
remove prezzo_totale column

2022-07-15 13:17 UTC, benedettapacilli approved these changes

2022-07-15 13:27 UTC, expl0r3rgu1 approved these changes

2022-07-15 13:27 UTC, merged